#!/bin/bash

# Author: toutain, vazov, 20a12, tt

# chkconfig:    35 87 15
# description: Galaxy start/stop daemon

. /etc/init.d/functions

start ()
{


## Check if apache httpd is running if exists
if ! type apachectl > /dev/null || apachectl status > /dev/null; then

    # Make sure galaxy tree exists
    if [ -d '/home/galaxy/galaxy' ]; then
        daemon --user="galaxy" /home/galaxy/galaxy/run.sh --daemon
        return 0
    else
        >&2 echo "Galaxy tree not found"
        return 1
    fi

else
    echo "Waiting for Apache to start..."
    apachectl restart
    daemon --user="galaxy" /home/galaxy/galaxy/run.sh --daemon
fi

}

stop ()
{
    /home/galaxy/galaxy/run.sh --stop-daemon
}


restart ()
{
    stop
    start
}


case "$1" in
    start) start; RETVAL=$? ;;
    stop) stop; RETVAL=$? ;;
    restart) restart; RETVAL=$? ;;
esac

exit $RETVAL
