#!/bin/bash

# Author: toutain, vazov, 20a12

# chkconfig:    35 87 15
# description: Galaxy start/stop daemon


. /etc/init.d/functions

start ()
{


## Check if apache is running
 
http_running="$(service httpd status)"
if [[ $http_running  == *"running"* ]]; then

echo "Apache is running ..."

# Make sure configuration file exists and has information we can use
    if [ -d '/home/galaxy/galaxy' ]; then
        daemon --user="galaxy" /home/galaxy/galaxy/run.sh --daemon
        return 0
    else
        sleep 120
        daemon --user="galaxy" /home//galaxy/galaxy/run.sh --daemon
    fi

else
    echo "Waiting for Apache to start..."
    sleep 120
    daemon --user="galaxy" /home/galaxy/galaxy/galaxy/run.sh --daemon
fi

}

stop ()
{
    /home/galaxy/galaxy/run.sh --stop-daemon
}


restart ()
{
    stop
    start
}


case "$1" in
    start) start; RETVAL=$? ;;
    stop) stop; RETVAL=$? ;;
    restart) restart; RETVAL=$? ;;
esac

exit $RETVAL
